import { defineContentConfig, defineCollection, z } from '@nuxt/content'

export default defineContentConfig({
    collections: {
        blog: defineCollection({
            type: 'page',
            source: 'blog/**/*.md',
            schema: z.object({
                title: z.string(),
                description: z.string(),
                image: z.string().optional(),
                imageAlt: z.string().optional(),
                date: z.string(),
                author: z.string().default('Seb'),
            }),
        }),

        // Hand-written copy for a public tab page. Never touched by the
        // exporter, so re-exporting a trip can't overwrite writing.
        trips: defineCollection({
            type: 'page',
            source: 'trips/**/*.md',
            schema: z.object({
                title: z.string(),
                description: z.string(),
                author: z.string().optional(),
                heading: z.string().optional(),
                ogTitle: z.string().optional(),
                ogDescription: z.string().optional(),
                image: z.string().optional(),
                imageAlt: z.string().optional(),
                blurb: z.string().optional(),
                date: z.string().optional(),
                order: z.number().default(0),
            }),
        }),

        // Generated by `manage.py export_public_tabs`. Do not hand-edit.
        // Body is the tab's own description, written as markdown in the app.
        tripData: defineCollection({
            type: 'page',
            source: 'tripdata/**/*.md',
            schema: z.object({
                slug: z.string(),
                name: z.string(),
                settlement_currency: z.string(),
                is_settled: z.boolean(),
                is_pro: z.boolean(),
                group_spend: z.number().nullable(),
                people: z.array(z.object({
                    id: z.string(),
                    name: z.string(),
                    spend: z.number(),
                })),
                settlements: z.array(z.object({
                    from_name: z.string(),
                    to_name: z.string(),
                    amount: z.number(),
                    currency: z.string(),
                    paid: z.boolean(),
                })),
                bills: z.array(z.object({
                    id: z.string(),
                    description: z.string(),
                    currency: z.string(),
                    date: z.string(),
                    total_amount: z.number(),
                    created_by: z.string(),
                    paid_by: z.string().nullable(),
                    has_receipt: z.boolean(),
                })),
                // Only read on the bill drill-down, so the overview query
                // selects around it rather than shipping it in every page.
                bill_details: z.array(z.object({
                    id: z.string(),
                    person_totals: z.array(z.object({
                        person_id: z.string(),
                        person_name: z.string(),
                        amount: z.number(),
                    })),
                    line_items: z.array(z.object({
                        id: z.string(),
                        description: z.string(),
                        value: z.number(),
                        split_type: z.string(),
                        claims: z.array(z.object({
                            person_id: z.string(),
                            person_name: z.string(),
                            split_value: z.number().nullable(),
                            amount: z.number().nullable(),
                        })),
                    })),
                })),
            }),
        }),

        authors: defineCollection({
            type: 'page',
            source: 'authors/**/*.md',
            schema: z.object({
                title: z.string(),
                description: z.string(),
                name: z.string(),
                flag: z.string().optional(),
                tagline: z.string().optional(),
                avatar: z.string().optional(),
                website: z.string().optional(),
                instagram: z.string().optional(),
                nationality: z.string().optional(),
                summary: z.string().optional(),
                knowsAbout: z.array(z.string()).default([]),
            }),
        }),
    },
})
